name: Build and Release CUDA Wheels

on:
  workflow_dispatch:

jobs:
  build_cuda_wheels:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9"]
        cuda: ["12.9.0"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.24
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda }}
          method: "network"
          log-file-suffix: "3.9.txt"
          use-github-cache: false
          use-local-cache: false

      - name: Set CUDA environment variables
        run: |
          echo "CUDA_HOME=${{ steps.cuda-toolkit.outputs.CUDA_HOME }}" >> $GITHUB_ENV
          echo "${{ steps.cuda-toolkit.outputs.CUDA_HOME }}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${{ steps.cuda-toolkit.outputs.CUDA_HOME }}/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Maturin
        run: pip install maturin>=1.8.6 numpy>=1.26.4

      - name: Build wheel
        id: build-wheels
        env:
          CUDA_COMPUTE_CAP: "80"
        run: maturin build --release --out dist

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-cuda-${{matrix.cuda}}-py${{ matrix.python-version }}
          path: dist/

  publish:
    name: Publish to PyPI
    needs: build_cuda_wheels
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
